spring.application.name=stockflow-backend

# Base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# JWT
security.jwt.secret.key=${JWT_SECRET_KEY}
security.jwt.user.generator=${JWT_USER_GENERATOR}

# Datos Usuario ADMIN
user.admin.username=${ADMIN_USERNAME}
user.admin.password=${ADMIN_PASSWORD}